### PR TITLE
add "examples" page on documentation

### PR DESCRIPTION
**Pull request by Nipodemos**
Hello again

sometimes when i am reading your docs, i want to go to the apps you made too see the code for myself.
Whenever i wanted this, it was necessary to open github, select you repo, navigate into the app folder...

This PR simplifies that problem.

But i want your opinion if it is a good way to put in documentation these links written "click here". If not, can you suggest me other way? i don't have any other idea, but i'm sure this can be better

also i am changing the `gh-pages` branch, don't know if it is the correct one. If is not, tell me.

### CODE REVIEW

**Comment by leisim** [comment]
Thanks for this PR. I like the idea but maybe we should also add a small description for the apps and what can be learned from each of them. This would also add a bit more content to this article.
You can either add them yourself or we merge the PR and I add them...

**Comment by Nipodemos** [comment]
i agree with you, in a few hours i can do these things

**Comment by leisim** [comment]
Oh and you also have to create the pull request against the master branch. Otherwise you changes will be lost with the next doc build.

**Comment by Nipodemos** [comment]
to be honest with you, i tried to put a small description of what you can learn with the apps, but i coudn't figure out what to put exacly in the docs.
Could you please add them later? i have no idea how to do it....
sorry for that

also i'm closing this PR to create another one against the master branch

**Pull request closed without merging**
